# -*- coding: utf-8 -*-
"""Software Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12uYxxj35vCvLbhq8l-05Ae1fmLoiiluy
"""

# ============================================================
# SMART MEETING ROOM ALLOCATION
# Streamlit Application
# ============================================================

import streamlit as st
import sqlite3
from datetime import datetime, date, time

# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Smart Meeting Room Allocation",
    page_icon="🏢",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============================================================
# DATABASE
# ============================================================

DB_NAME = "meeting_rooms.db"


def get_connection():
    return sqlite3.connect(DB_NAME, check_same_thread=False)


conn = get_connection()
cursor = conn.cursor()


# ============================================================
# CREATE DATABASE TABLES
# ============================================================

cursor.execute("""
CREATE TABLE IF NOT EXISTS rooms (
    room_id INTEGER PRIMARY KEY AUTOINCREMENT,
    room_name TEXT UNIQUE NOT NULL,
    capacity INTEGER NOT NULL,
    facilities TEXT NOT NULL
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS bookings (
    booking_id INTEGER PRIMARY KEY AUTOINCREMENT,
    meeting_name TEXT NOT NULL,
    organizer TEXT NOT NULL,
    participants INTEGER NOT NULL,
    room_id INTEGER NOT NULL,
    booking_date TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    FOREIGN KEY(room_id) REFERENCES rooms(room_id)
)
""")

conn.commit()


# ============================================================
# INSERT DEFAULT ROOMS
# ============================================================

default_rooms = [
    ("Room A", 4, "None"),
    ("Room B", 8, "Projector"),
    ("Room C", 12, "Projector, Whiteboard"),
    ("Room D", 20, "Projector, Whiteboard")
]

for room in default_rooms:
    cursor.execute(
        "SELECT room_id FROM rooms WHERE room_name = ?",
        (room[0],)
    )

    if cursor.fetchone() is None:
        cursor.execute("""
        INSERT INTO rooms (room_name, capacity, facilities)
        VALUES (?, ?, ?)
        """, room)

conn.commit()


# ============================================================
# CUSTOM CSS
# IMPORTANT:
# Styling is kept inside st.markdown only.
# It is NOT displayed as normal text.
# ============================================================

st.markdown("""
<style>

    /* Main background */

    .stApp {
        background-color: #f5f7fb;
    }

    /* Main title */

    .main-title {
        font-size: 42px;
        font-weight: 800;
        color: #172554;
        margin-bottom: 5px;
    }

    .subtitle {
        font-size: 17px;
        color: #64748b;
        margin-bottom: 25px;
    }

    /* Dashboard cards */

    .dashboard-card {
        background-color: white;
        padding: 22px;
        border-radius: 16px;
        border: 1px solid #e2e8f0;
        box-shadow: 0px 4px 12px rgba(15, 23, 42, 0.06);
        min-height: 120px;
    }

    .dashboard-title {
        font-size: 15px;
        color: #64748b;
        font-weight: 600;
    }

    .dashboard-number {
        font-size: 32px;
        font-weight: 800;
        color: #172554;
        margin-top: 8px;
    }

    /* Room cards */

    .room-card {
        background-color: white;
        padding: 20px;
        border-radius: 16px;
        border: 1px solid #e2e8f0;
        box-shadow: 0px 4px 12px rgba(15, 23, 42, 0.05);
        margin-bottom: 10px;
    }

    .room-name {
        font-size: 22px;
        font-weight: 750;
        color: #172554;
    }

    .room-capacity {
        font-size: 16px;
        color: #475569;
        margin-top: 8px;
    }

    .room-facility {
        font-size: 14px;
        color: #64748b;
        margin-top: 7px;
    }

    .available {
        color: #15803d;
        font-weight: 700;
    }

    .occupied {
        color: #dc2626;
        font-weight: 700;
    }

    /* Section headings */

    .section-heading {
        font-size: 27px;
        font-weight: 750;
        color: #172554;
        margin-top: 25px;
        margin-bottom: 15px;
    }

    /* Booking confirmation */

    .success-box {
        background-color: #ecfdf5;
        border: 1px solid #86efac;
        border-radius: 16px;
        padding: 22px;
        margin-top: 20px;
    }

    .success-title {
        color: #166534;
        font-size: 25px;
        font-weight: 800;
    }

    .success-text {
        color: #166534;
        font-size: 16px;
        margin-top: 8px;
    }

    /* Sidebar */

    section[data-testid="stSidebar"] {
        background-color: #172554;
    }

    section[data-testid="stSidebar"] * {
        color: white;
    }

</style>
""", unsafe_allow_html=True)


# ============================================================
# FUNCTIONS
# ============================================================

def get_rooms():

    cursor.execute("""
    SELECT room_id, room_name, capacity, facilities
    FROM rooms
    ORDER BY capacity
    """)

    return cursor.fetchall()


def get_booked_room_ids(selected_date):

    cursor.execute("""
    SELECT DISTINCT room_id
    FROM bookings
    WHERE booking_date = ?
    """, (selected_date,))

    return [row[0] for row in cursor.fetchall()]


def is_room_available(
    room_id,
    selected_date,
    start_time,
    end_time
):

    cursor.execute("""
    SELECT booking_id
    FROM bookings
    WHERE room_id = ?
    AND booking_date = ?
    AND start_time < ?
    AND end_time > ?
    """, (
        room_id,
        selected_date,
        end_time,
        start_time
    ))

    return cursor.fetchone() is None


def has_required_facilities(
    room_facilities,
    required_facilities
):

    if not required_facilities:
        return True

    if "None" in room_facilities:
        return False

    room_facilities = room_facilities.lower()

    for facility in required_facilities:

        if facility.lower() not in room_facilities:
            return False

    return True


def find_best_room(
    participants,
    required_facilities,
    selected_date,
    start_time,
    end_time
):

    rooms = get_rooms()

    suitable_rooms = []

    for room in rooms:

        room_id = room[0]
        room_name = room[1]
        capacity = room[2]
        facilities = room[3]

        # Capacity check
        if capacity < participants:
            continue

        # Facility check
        if not has_required_facilities(
            facilities,
            required_facilities
        ):
            continue

        # Time availability check
        if not is_room_available(
            room_id,
            selected_date,
            start_time,
            end_time
        ):
            continue

        suitable_rooms.append(room)

    # Select smallest suitable room
    if suitable_rooms:
        return suitable_rooms[0]

    return None


def get_current_bookings(selected_date):

    cursor.execute("""
    SELECT
        bookings.booking_id,
        bookings.meeting_name,
        bookings.organizer,
        bookings.participants,
        rooms.room_name,
        bookings.start_time,
        bookings.end_time
    FROM bookings
    JOIN rooms
    ON bookings.room_id = rooms.room_id
    WHERE bookings.booking_date = ?
    ORDER BY bookings.start_time
    """, (selected_date,))

    return cursor.fetchall()


def get_room_status(room_id, selected_date):

    cursor.execute("""
    SELECT booking_id
    FROM bookings
    WHERE room_id = ?
    AND booking_date = ?
    """, (room_id, selected_date))

    return cursor.fetchone() is not None


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.markdown("## 🏢 Meeting Manager")

    st.markdown("---")

    page = st.radio(
        "Navigation",
        [
            "🏠 Dashboard",
            "📅 Book a Room",
            "📋 Bookings",
            "🏢 Room Information"
        ]
    )

    st.markdown("---")

    st.markdown(
        "### Smart Allocation"
    )

    st.write(
        "Automatically assigns the most suitable "
        "available room based on capacity, "
        "facilities and schedule."
    )


# ============================================================
# HEADER
# ============================================================

st.markdown(
    '<div class="main-title">🏢 SMART MEETING ROOM ALLOCATION</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">'
    'Intelligent room booking and resource management system'
    '</div>',
    unsafe_allow_html=True
)


# ============================================================
# DASHBOARD
# ============================================================

if page == "🏠 Dashboard":

    rooms = get_rooms()

    selected_date = date.today().strftime("%Y-%m-%d")

    cursor.execute("""
    SELECT COUNT(*)
    FROM bookings
    WHERE booking_date = ?
    """, (selected_date,))

    booked_count = cursor.fetchone()[0]

    total_rooms = len(rooms)

    available_rooms = total_rooms - booked_count

    total_capacity = sum(room[2] for room in rooms)

    # --------------------------------------------------------
    # DASHBOARD METRICS
    # --------------------------------------------------------

    col1, col2, col3, col4 = st.columns(4)

    with col1:

        st.markdown("""
        <div class="dashboard-card">
            <div class="dashboard-title">
                🏢 Total Rooms
            </div>
            <div class="dashboard-number">
                4
            </div>
        </div>
        """, unsafe_allow_html=True)

    with col2:

        st.markdown(f"""
        <div class="dashboard-card">
            <div class="dashboard-title">
                🟢 Available Rooms
            </div>
            <div class="dashboard-number">
                {available_rooms}
            </div>
        </div>
        """, unsafe_allow_html=True)

    with col3:

        st.markdown(f"""
        <div class="dashboard-card">
            <div class="dashboard-title">
                🔴 Booked Rooms
            </div>
            <div class="dashboard-number">
                {booked_count}
            </div>
        </div>
        """, unsafe_allow_html=True)

    with col4:

        st.markdown(f"""
        <div class="dashboard-card">
            <div class="dashboard-title">
                👥 Total Capacity
            </div>
            <div class="dashboard-number">
                {total_capacity}
            </div>
        </div>
        """, unsafe_allow_html=True)

    # --------------------------------------------------------
    # ROOMS
    # --------------------------------------------------------

    st.markdown(
        '<div class="section-heading">🏢 Meeting Rooms</div>',
        unsafe_allow_html=True
    )

    room_columns = st.columns(2)

    for index, room in enumerate(rooms):

        room_id = room[0]
        room_name = room[1]
        capacity = room[2]
        facilities = room[3]

        occupied = get_room_status(
            room_id,
            selected_date
        )

        with room_columns[index % 2]:

            if occupied:
                status = "🔴 BOOKED"
                status_class = "occupied"
            else:
                status = "🟢 AVAILABLE"
                status_class = "available"

            st.markdown(f"""
            <div class="room-card">

                <div class="room-name">
                    {room_name}
                </div>

                <div class="room-capacity">
                    👥 Accommodates up to
                    <strong>{capacity} participants</strong>
                </div>

                <div class="room-facility">
                    🛠️ Facilities:
                    <strong>{facilities}</strong>
                </div>

                <div class="{status_class}"
                     style="margin-top:12px;">
                    {status}
                </div>

            </div>
            """, unsafe_allow_html=True)


# ============================================================
# BOOK ROOM
# ============================================================

elif page == "📅 Book a Room":

    st.markdown(
        '<div class="section-heading">📅 Book a Meeting Room</div>',
        unsafe_allow_html=True
    )

    st.info(
        "The system will automatically select the smallest "
        "suitable room that satisfies your requirements."
    )

    col1, col2 = st.columns(2)

    with col1:

        meeting_name = st.text_input(
            "Meeting Name",
            placeholder="Example: Project Discussion"
        )

        organizer = st.text_input(
            "Organizer",
            placeholder="Enter organizer name"
        )

        participants = st.number_input(
            "Number of Participants",
            min_value=1,
            max_value=100,
            value=4,
            step=1
        )

    with col2:

        booking_date = st.date_input(
            "Meeting Date",
            value=date.today()
        )

        start_time = st.time_input(
            "Start Time",
            value=time(9, 0)
        )

        end_time = st.time_input(
            "End Time",
            value=time(10, 0)
        )

    st.markdown("### 🛠️ Required Facilities")

    facility_options = [
        "Projector",
        "Whiteboard"
    ]

    required_facilities = st.multiselect(
        "Select facilities",
        facility_options
    )

    st.markdown("")

    if st.button(
        "🚀 Allocate Meeting Room",
        type="primary",
        use_container_width=True
    ):

        # ----------------------------------------------------
        # VALIDATION
        # ----------------------------------------------------

        if not meeting_name.strip():

            st.error(
                "Please enter the meeting name."
            )

        elif not organizer.strip():

            st.error(
                "Please enter the organizer name."
            )

        elif end_time <= start_time:

            st.error(
                "End time must be after start time."
            )

        else:

            selected_date = booking_date.strftime(
                "%Y-%m-%d"
            )

            start_string = start_time.strftime(
                "%H:%M"
            )

            end_string = end_time.strftime(
                "%H:%M"
            )

            # ------------------------------------------------
            # FIND ROOM
            # ------------------------------------------------

            room = find_best_room(
                participants,
                required_facilities,
                selected_date,
                start_string,
                end_string
            )

            if room is None:

                st.error(
                    "❌ No suitable room is available "
                    "for the selected requirements and time."
                )

            else:

                room_id = room[0]
                room_name = room[1]
                capacity = room[2]
                facilities = room[3]

                # --------------------------------------------
                # INSERT BOOKING
                # --------------------------------------------

                cursor.execute("""
                INSERT INTO bookings (
                    meeting_name,
                    organizer,
                    participants,
                    room_id,
                    booking_date,
                    start_time,
                    end_time
                )
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """, (
                    meeting_name,
                    organizer,
                    participants,
                    room_id,
                    selected_date,
                    start_string,
                    end_string
                ))

                conn.commit()

                # --------------------------------------------
                # SUCCESS MESSAGE
                # --------------------------------------------

                st.markdown(f"""
                <div class="success-box">

                    <div class="success-title">
                        ✅ YOUR SLOT IS BOOKED!
                    </div>

                    <div class="success-text">

                        <strong>Meeting:</strong>
                        {meeting_name}
                        <br><br>

                        <strong>Room:</strong>
                        {room_name}
                        <br>

                        <strong>Participants:</strong>
                        {participants}
                        <br>

                        <strong>Date:</strong>
                        {selected_date}
                        <br>

                        <strong>Time:</strong>
                        {start_string} - {end_string}
                        <br>

                        <strong>Facilities:</strong>
                        {facilities}

                    </div>

                </div>
                """, unsafe_allow_html=True)

                st.balloons()


# ============================================================
# BOOKINGS
# ============================================================

elif page == "📋 Bookings":

    st.markdown(
        '<div class="section-heading">📋 Meeting Schedule</div>',
        unsafe_allow_html=True
    )

    selected_date = st.date_input(
        "Select Date",
        value=date.today(),
        key="booking_view_date"
    )

    selected_date_string = selected_date.strftime(
        "%Y-%m-%d"
    )

    bookings = get_current_bookings(
        selected_date_string
    )

    if not bookings:

        st.info(
            "No meetings are scheduled for this date."
        )

    else:

        for booking in bookings:

            booking_id = booking[0]
            meeting_name = booking[1]
            organizer = booking[2]
            participants = booking[3]
            room_name = booking[4]
            start = booking[5]
            end = booking[6]

            with st.container(border=True):

                col1, col2, col3 = st.columns(
                    [3, 2, 2]
                )

                with col1:

                    st.markdown(
                        f"### 📌 {meeting_name}"
                    )

                    st.write(
                        f"Organizer: **{organizer}**"
                    )

                with col2:

                    st.write(
                        f"🏢 **{room_name}**"
                    )

                    st.write(
                        f"👥 {participants} participants"
                    )

                with col3:

                    st.write(
                        f"⏰ {start} - {end}"
                    )

                    if st.button(
                        "Cancel",
                        key=f"cancel_{booking_id}"
                    ):

                        cursor.execute("""
                        DELETE FROM bookings
                        WHERE booking_id = ?
                        """, (booking_id,))

                        conn.commit()

                        st.success(
                            "Booking cancelled successfully."
                        )

                        st.rerun()


# ============================================================
# ROOM INFORMATION
# ============================================================

elif page == "🏢 Room Information":

    st.markdown(
        '<div class="section-heading">'
        '🏢 Room Information'
        '</div>',
        unsafe_allow_html=True
    )

    rooms = get_rooms()

    for room in rooms:

        room_id = room[0]
        room_name = room[1]
        capacity = room[2]
        facilities = room[3]

        with st.container(border=True):

            col1, col2, col3 = st.columns(
                [2, 2, 3]
            )

            with col1:

                st.markdown(
                    f"### 🏢 {room_name}"
                )

            with col2:

                st.write(
                    f"👥 Capacity: **{capacity}**"
                )

            with col3:

                st.write(
                    f"🛠️ Facilities: **{facilities}**"
                )


# ============================================================
# FOOTER
# ============================================================

st.markdown("---")

st.caption(
    "Smart Meeting Room Allocation System • "
    "Python + Streamlit + SQLite"
)